#' Generate an automated EDA report for a dataset
#'
#' This function creates a comprehensive HTML report with data summaries,
#' missing value analysis, correlation analysis, and outlier detection.
#'
#' @param data A dataframe to analyze
#' @param output_file Character, the path to save the HTML report (default: "eda_report.html")
#' @param title Character, the title for the report (default: "Exploratory Data Analysis Report")
#' @param author Character, the author name to include in the report (default: NULL)
#' @param include_code Logical, whether to include R code in the report (default: FALSE)
#' @param theme Character, the theme to use for the report (default: "cosmo")
#' @param toc Logical, whether to include a table of contents (default: TRUE)
#' @param correlation_method Character, the correlation method to use (default: "pearson")
#' @param outlier_methods Character vector of outlier detection methods (default: c("iqr", "zscore"))
#' @param additional_options List of additional options for the report, including:
#'   \itemize{
#'     \item include_summary: Logical, whether to include data summary (default: TRUE)
#'     \item include_missing: Logical, whether to include missing data analysis (default: TRUE)
#'     \item include_correlations: Logical, whether to include correlation analysis (default: TRUE)
#'     \item include_outliers: Logical, whether to include outlier detection (default: TRUE)
#'     \item include_subgroup: Logical, whether to include subgroup analysis (default: FALSE)
#'     \item subgroup_var: Character, target variable for subgroup analysis
#'     \item subgroup_by: Character, grouping variable for subgroup analysis
#'     \item subgroup_plot_type: Character, plot type for subgroup analysis
#'     \item subgroup_facet: Logical, whether to use facet wrap for subgroup plots
#'     \item subgroup_normalize: Logical, whether to normalize values in subgroup plots
#'     \item include_models: Logical, whether to include model recommendations (default: FALSE)
#'     \item model_recommendations: Model recommendations object
#'   }
#' @return The file path to the generated report (invisibly)
#' @export
#'
#' @examples
#' \dontrun{
#' generate_eda_report(iris, output_file = "iris_eda_report.html")
#' generate_eda_report(mtcars, title = "Analysis of Motor Trend Car Road Tests")
#' }
generate_eda_report <- function(data, output_file = "eda_report.html", 
                               title = "Exploratory Data Analysis Report",
                               author = NULL, include_code = FALSE,
                               theme = "cosmo", toc = TRUE,
                               correlation_method = "pearson",
                               outlier_methods = c("iqr", "zscore"),
                               additional_options = NULL) {
  
  # Check required packages
  required_packages <- c("rmarkdown", "knitr")
  for (pkg in required_packages) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
      stop(paste("Package", pkg, "is required but not installed. Install with install.packages('", pkg, "')"))
    }
  }
  
  # Generate a temporary Rmd file
  rmd_file <- tempfile(fileext = ".Rmd")
  
  # Process additional options
  if (is.null(additional_options)) {
    additional_options <- list(
      include_summary = TRUE,
      include_missing = TRUE,
      include_correlations = TRUE,
      include_outliers = TRUE,
      include_subgroup = FALSE,
      include_models = FALSE
    )
  } else {
    # Set defaults for missing options
    if (is.null(additional_options$include_summary)) additional_options$include_summary <- TRUE
    if (is.null(additional_options$include_missing)) additional_options$include_missing <- TRUE
    if (is.null(additional_options$include_correlations)) additional_options$include_correlations <- TRUE
    if (is.null(additional_options$include_outliers)) additional_options$include_outliers <- TRUE
    if (is.null(additional_options$include_subgroup)) additional_options$include_subgroup <- FALSE
    if (is.null(additional_options$include_models)) additional_options$include_models <- FALSE
  }
  
  # Create the R Markdown content
  rmd_content <- paste0(
    "---\n",
    "title: \"", title, "\"\n",
    if (!is.null(author)) paste0("author: \"", author, "\"\n") else "",
    "date: \"", format(Sys.time(), "%Y-%m-%d"), "\"\n",
    "output:\n",
    "  html_document:\n",
    "    theme: ", theme, "\n",
    "    toc: ", tolower(as.character(toc)), "\n",
    "    toc_float: true\n",
    "    code_folding: ", if (include_code) "show" else "hide", "\n",
    "---\n\n",
    
    "```{r setup, include=FALSE}\n",
    "knitr::opts_chunk$set(echo = ", ifelse(include_code, "TRUE", "FALSE"),
    ", message = FALSE, warning = FALSE, fig.width = 10, fig.height = 6)\n",
    "library(EDAhelper)\n",
    "```\n\n",
    
    "## Dataset Overview\n\n",
    "This report provides an exploratory data analysis of the dataset, which contains ",
    "`r nrow(data)` observations and `r ncol(data)` variables.\n\n",
    
    "```{r data_preview}\n",
    "# Display the first few rows of the data\n",
    "if (nrow(data) > 0) {\n",
    "  head(data, min(6, nrow(data)))\n",
    "}\n\n",
    "# Get data summary\n",
    "data_summary_result <- data_summary(data)\n",
    "```\n\n",
    
    "## Data Summary\n\n",
    "### Basic Information\n\n",
    "```{r basic_info}\n",
    "# Display basic information\n",
    "cat(\"Dimensions:\", data_summary_result$overview$dimensions[1], \"rows,\",\n",
    "    data_summary_result$overview$dimensions[2], \"columns\\n\")\n",
    "cat(\"Memory usage:\", format(data_summary_result$overview$memory_usage, units = \"auto\"), \"\\n\\n\")\n\n",
    "cat(\"Column Types:\\n\")\n",
    "type_table <- table(unlist(data_summary_result$overview$column_types))\n",
    "for (type in names(type_table)) {\n",
    "  cat(\" -\", type, \":\", type_table[type], \"columns\\n\")\n",
    "}\n",
    "```\n\n",
    
    "### Numeric Variables\n\n",
    "```{r numeric_summary}\n",
    "# Check if there are numeric variables\n",
    "if (!is.null(data_summary_result$numeric_summary)) {\n",
    "  # Create a summary table\n",
    "  num_vars <- names(data_summary_result$numeric_summary)\n",
    "  num_summary_df <- data.frame(\n",
    "    Variable = num_vars,\n",
    "    Mean = sapply(data_summary_result$numeric_summary, function(x) round(x$mean, 2)),\n",
    "    Median = sapply(data_summary_result$numeric_summary, function(x) round(x$median, 2)),\n",
    "    Min = sapply(data_summary_result$numeric_summary, function(x) round(x$min, 2)),\n",
    "    Max = sapply(data_summary_result$numeric_summary, function(x) round(x$max, 2)),\n",
    "    StdDev = sapply(data_summary_result$numeric_summary, function(x) round(x$sd, 2)),\n",
    "    Missing = sapply(data_summary_result$numeric_summary, function(x) x$missing),\n",
    "    MissingPct = sapply(data_summary_result$numeric_summary, function(x) round(x$percent_missing, 1))\n",
    "  )\n",
    "  knitr::kable(num_summary_df, caption = \"Summary of Numeric Variables\")\n",
    "  \n",
    "  # Display histograms\n",
    "  if (!is.null(data_summary_result$plots$numeric)) {\n",
    "    cat(\"\\n\\n### Distributions of Numeric Variables\\n\\n\")\n",
    "    for (i in seq_along(data_summary_result$plots$numeric)) {\n",
    "      print(data_summary_result$plots$numeric[[i]])\n",
    "    }\n",
    "  }\n",
    "} else {\n",
    "  cat(\"No numeric variables in the dataset.\")\n",
    "}\n",
    "```\n\n",
    
    "### Categorical Variables\n\n",
    "```{r categorical_summary}\n",
    "# Check if there are categorical variables\n",
    "if (!is.null(data_summary_result$categorical_summary) && length(data_summary_result$categorical_summary) > 0) {\n",
    "  # Create a summary table\n",
    "  cat_vars <- names(data_summary_result$categorical_summary)\n",
    "  cat_summary_df <- data.frame(\n",
    "    Variable = cat_vars,\n",
    "    Unique = sapply(data_summary_result$categorical_summary, function(x) x$n_unique),\n",
    "    Mode = sapply(data_summary_result$categorical_summary, function(x) as.character(x$mode)),\n",
    "    Missing = sapply(data_summary_result$categorical_summary, function(x) x$missing),\n",
    "    MissingPct = sapply(data_summary_result$categorical_summary, function(x) round(x$percent_missing, 1))\n",
    "  )\n",
    "  knitr::kable(cat_summary_df, caption = \"Summary of Categorical Variables\")\n",
    "  \n",
    "  # Display bar plots\n",
    "  if (!is.null(data_summary_result$plots$categorical)) {\n",
    "    cat(\"\\n\\n### Distributions of Categorical Variables\\n\\n\")\n",
    "    for (i in seq_along(data_summary_result$plots$categorical)) {\n",
    "      if (!is.null(data_summary_result$plots$categorical[[i]])) {\n",
    "        print(data_summary_result$plots$categorical[[i]])\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  \n",
    "  # Display frequency tables for variables with few categories\n",
    "  cat(\"\\n\\n### Frequency Tables for Categorical Variables\\n\\n\")\n",
    "  for (var in cat_vars) {\n",
    "    if (data_summary_result$categorical_summary[[var]]$n_unique <= 10) {\n",
    "      cat(\"#### \", var, \"\\n\\n\")\n",
    "      # Convert table to data frame safely\n",
    "      freq_counts <- as.vector(data_summary_result$categorical_summary[[var]]$frequencies)\n",
    "      freq_names <- names(data_summary_result$categorical_summary[[var]]$frequencies)\n",
    "      freq_table <- data.frame(\n",
    "        Value = freq_names,\n",
    "        Frequency = freq_counts,\n",
    "        stringsAsFactors = FALSE\n",
    "      )\n",
    "      # Calculate percentage safely\n",
    "      total_count <- sum(freq_counts)\n",
    "      freq_table$Percentage <- (freq_table$Frequency / total_count) * 100\n",
    "      knitr::kable(freq_table, row.names = FALSE, digits = 1)\n",
    "      cat(\"\\n\\n\")\n",
    "    }\n",
    "  }\n",
    "} else {\n",
    "  cat(\"No categorical variables in the dataset.\")\n",
    "}\n",
    "```\n\n",
    
    "## Missing Value Analysis\n\n",
    "```{r missing_analysis}\n",
    "# Run missing value analysis\n",
    "missing_result <- missing_analysis(data)\n\n",
    "# Display overall summary\n",
    "cat(\"### Overall Missing Value Summary\\n\\n\")\n",
    "cat(\"Total cells:\", missing_result$overall$total_cells, \"\\n\")\n",
    "cat(\"Missing cells:\", missing_result$overall$missing_cells, \n",
    "    \"(\", round(missing_result$overall$missing_percent, 1), \"%)\\n\")\n",
    "cat(\"Complete rows:\", missing_result$overall$complete_rows, \n",
    "    \"(\", round(100 - missing_result$overall$incomplete_row_percent, 1), \"%)\\n\")\n",
    "cat(\"Incomplete rows:\", missing_result$overall$incomplete_rows, \n",
    "    \"(\", round(missing_result$overall$incomplete_row_percent, 1), \"%)\\n\\n\")\n\n",
    
    "# Display missing by column if there are any missing values\n",
    "if (missing_result$overall$missing_cells > 0) {\n",
    "  cat(\"### Missing Values by Column\\n\\n\")\n",
    "  missing_by_col <- data.frame(\n",
    "    Column = names(missing_result$columns),\n",
    "    Missing = sapply(missing_result$columns, function(x) x$missing_count),\n",
    "    Percentage = sapply(missing_result$columns, function(x) round(x$missing_percent, 1))\n",
    "  )\n",
    "  missing_by_col <- missing_by_col[order(-missing_by_col$Percentage), ]\n",
    "  knitr::kable(missing_by_col)\n",
    "  \n",
    "  # Display plots if available\n",
    "  if (!is.null(missing_result$plots)) {\n",
    "    if (!is.null(missing_result$plots$column_plot)) {\n",
    "      cat(\"\\n\\n\")\n",
    "      print(missing_result$plots$column_plot)\n",
    "    }\n",
    "    \n",
    "    if (!is.null(missing_result$plots$heatmap)) {\n",
    "      cat(\"\\n\\n\")\n",
    "      print(missing_result$plots$heatmap)\n",
    "    }\n",
    "    \n",
    "    if (!is.null(missing_result$plots$correlation)) {\n",
    "      cat(\"\\n\\n### Missing Value Correlation\\n\\n\")\n",
    "      cat(\"This plot shows the correlation between missing values in different columns. \",\n",
    "          \"A high correlation indicates that values tend to be missing in the same rows.\\n\\n\")\n",
    "      print(missing_result$plots$correlation)\n",
    "    }\n",
    "  }\n",
    "}\n",
    "```\n\n",
    
    "## Correlation Analysis\n\n",
    "```{r correlation_analysis}\n",
    "# Run correlation analysis\n",
    "corr_result <- correlation_analysis(data, method = \"", correlation_method, "\")\n\n",
    "# Display numeric correlations if available\n",
    "if (!is.null(corr_result$numeric_correlation)) {\n",
    "  cat(\"### Numeric Variable Correlations\\n\\n\")\n",
    "  \n",
    "  # Display correlation matrix\n",
    "  corr_matrix <- round(corr_result$numeric_correlation, 2)\n",
    "  knitr::kable(corr_matrix, caption = paste0(\"Correlation Matrix (method: \", \"", correlation_method, "\", \")\"))\n",
    "  \n",
    "  # Display correlation plot\n",
    "  if (!is.null(corr_result$plots$numeric)) {\n",
    "    cat(\"\\n\\n\")\n",
    "    corr_result$plots$numeric()\n",
    "  }\n",
    "  \n",
    "  # Display pairplot if available\n",
    "  if (!is.null(corr_result$plots$pairplot)) {\n",
    "    cat(\"\\n\\n### Pairwise Relationships Between Numeric Variables\\n\\n\")\n",
    "    corr_result$plots$pairplot()\n",
    "  }\n",
    "  \n",
    "  # Display strong correlations if any\n",
    "  if (!is.null(corr_result$strong_correlations)) {\n",
    "    cat(\"\\n\\n### Strong Correlations\\n\\n\")\n",
    "    sc_df <- corr_result$strong_correlations\n",
    "    sc_df$correlation <- round(sc_df$correlation, 2)\n",
    "    knitr::kable(sc_df, col.names = c(\"Variable 1\", \"Variable 2\", \"Correlation\"))\n",
    "  }\n",
    "} else {\n",
    "  cat(\"No numeric correlations to display (requires at least 2 numeric variables).\")\n",
    "}\n\n",
    
    "# Display categorical correlations if available\n",
    "if (!is.null(corr_result$categorical_correlation)) {\n",
    "  cat(\"\\n\\n### Categorical Variable Correlations (Cramer's V)\\n\\n\")\n",
    "  \n",
    "  # Display correlation matrix\n",
    "  cat_corr_matrix <- round(corr_result$categorical_correlation, 2)\n",
    "  knitr::kable(cat_corr_matrix, caption = \"Categorical Correlation Matrix (Cramer's V)\")\n",
    "  \n",
    "  # Display correlation plot\n",
    "  if (!is.null(corr_result$plots$categorical)) {\n",
    "    cat(\"\\n\\n\")\n",
    "    corr_result$plots$categorical()\n",
    "  }\n",
    "}\n\n",
    
    "# Display mixed correlations if available\n",
    "if (!is.null(corr_result$mixed_correlation)) {\n",
    "  cat(\"\\n\\n### Numeric-Categorical Correlations (Correlation Ratio - Eta)\\n\\n\")\n",
    "  \n",
    "  # Display correlation matrix\n",
    "  mixed_corr_matrix <- round(corr_result$mixed_correlation, 2)\n",
    "  knitr::kable(mixed_corr_matrix, caption = \"Numeric-Categorical Correlation Matrix (Eta)\")\n",
    "  \n",
    "  # Display correlation plot\n",
    "  if (!is.null(corr_result$plots$mixed)) {\n",
    "    cat(\"\\n\\n\")\n",
    "    corr_result$plots$mixed()\n",
    "  }\n",
    "}\n",
    "```\n\n",
    
    "## Outlier Detection\n\n",
    "```{r outlier_detection}\n",
    "# Run outlier detection\n",
    "outlier_result <- outlier_detection(data, methods = outlier_methods)\n\n",
    "# Display summary by method\n",
    "cat(\"### Outliers by Method\\n\\n\")\n",
    "outlier_summary <- data.frame(Method = character(), Count = numeric())\n",
    "for (method in names(outlier_result$summary)) {\n",
    "  if (method != \"per_variable\") {\n",
    "    outlier_summary <- rbind(outlier_summary, \n",
    "                             data.frame(Method = method, \n",
    "                                        Count = outlier_result$summary[[method]]))\n",
    "  }\n",
    "}\n",
    "knitr::kable(outlier_summary)\n\n",
    
    "# Display summary by variable if there are outliers\n",
    "if (!is.null(outlier_result$summary$per_variable) && ncol(outlier_result$summary$per_variable) > 0) {\n",
    "  # Only process numeric variables for outliers\n",
    "  numeric_cols <- sapply(data, is.numeric)\n",
    "  numeric_var_names <- names(data)[numeric_cols]\n",
    "  \n",
    "  # Filter per_variable to only include numeric columns\n",
    "  per_var_cols <- intersect(colnames(outlier_result$summary$per_variable), numeric_var_names)\n",
    "  \n",
    "  if (length(per_var_cols) > 0) {\n",
    "    per_var_numeric <- outlier_result$summary$per_variable[, per_var_cols, drop=FALSE]\n",
    "    \n",
    "    var_summary <- data.frame(\n",
    "      Variable = colnames(per_var_numeric),\n",
    "      Methods = apply(per_var_numeric > 0, 2, sum),\n",
    "      Total = apply(per_var_numeric, 2, sum)\n",
    "    )\n",
    "    var_summary <- var_summary[var_summary$Total > 0, ]\n",
    "  } else {\n",
    "    var_summary <- data.frame(Variable=character(0), Methods=numeric(0), Total=numeric(0))\n",
    "  }\n",
    "  \n",
    "  if (nrow(var_summary) > 0) {\n",
    "    cat(\"\\n\\n### Outliers by Variable\\n\\n\")\n",
    "    knitr::kable(var_summary, col.names = c(\"Variable\", \"Methods Detecting Outliers\", \"Total Outliers\"))\n",
    "    \n",
    "    # Display plots for variables with outliers\n",
    "    cat(\"\\n\\n### Visualizations of Outliers\\n\\n\")\n",
    "    for (var in var_summary$Variable) {\n",
    "      # First display boxplot\n",
    "      if (!is.null(outlier_result$plots[[var]])) {\n",
    "        cat(paste0(\"#### \", var, \"\\n\\n\"))\n",
    "        print(outlier_result$plots[[var]])\n",
    "        \n",
    "        # Then display scatter plot if available\n",
    "        scatter_name <- paste0(var, \"_scatter\")\n",
    "        if (!is.null(outlier_result$plots[[scatter_name]])) {\n",
    "          cat(\"\\n\\n\")\n",
    "          print(outlier_result$plots[[scatter_name]])\n",
    "        }\n",
    "        cat(\"\\n\\n\")\n",
    "      }\n",
    "    }\n",
    "    \n",
    "    # Display DBSCAN result if available\n",
    "    if (!is.null(outlier_result$plots$dbscan_pairplot)) {\n",
    "      cat(\"\\n\\n### DBSCAN Outlier Detection\\n\\n\")\n",
    "      cat(\"DBSCAN identifies outliers by finding clusters of points in the dataset. \",\n",
    "          \"Points that don't belong to any cluster are considered outliers.\\n\\n\")\n",
    "      outlier_result$plots$dbscan_pairplot()\n",
    "    }\n",
    "  } else {\n",
    "    cat(\"\\n\\nNo outliers detected in the dataset.\")\n",
    "  }\n",
    "} else {\n",
    "  cat(\"\\n\\nNo outliers detected in the dataset.\")\n",
    "}\n",
    "```\n\n",
    
    if (additional_options$include_subgroup && !is.null(additional_options$subgroup_var) && !is.null(additional_options$subgroup_by)) {
      paste0(
        "## Subgroup Analysis\n\n",
        "```{r subgroup_analysis}\n",
        "# Subgroup Analysis\n",
        "cat(\"### Distribution of \", \"", additional_options$subgroup_var, "\", \" by \", \"", additional_options$subgroup_by, "\"\\n\\n\")\n\n",
        
        "# Create filtered data\n",
        "subgroup_data <- data\n\n",
        
        "# Select variables of interest\n",
        "target_var <- \"", additional_options$subgroup_var, "\"\n",
        "group_var <- \"", additional_options$subgroup_by, "\"\n\n",
        
        "# Handle missing values in grouping variable\n",
        "subgroup_data[[group_var]][is.na(subgroup_data[[group_var]])] <- \"Missing\"\n",
        "subgroup_data[[group_var]] <- factor(subgroup_data[[group_var]])\n\n",
        
        "# Create plot\n",
        "if (is.numeric(subgroup_data[[target_var]])) {\n",
        "  # For numeric target variables\n",
        "  if (\"", additional_options$subgroup_plot_type, "\" == \"hist\") {\n",
        "    # Histogram\n",
        "    p <- ggplot(subgroup_data, aes_string(x = target_var, fill = group_var)) +\n",
        "      geom_histogram(bins = 30, alpha = 0.7, position = ", 
                             ifelse(additional_options$subgroup_normalize, "\"fill\"", "\"stack\""), ") +\n",
        "      ", ifelse(additional_options$subgroup_facet, "facet_wrap(~ subgroup_data[[group_var]], scales = \"free_y\") +\n", ""),
        "      scale_fill_viridis_d() +\n",
        "      theme_minimal() +\n",
        "      labs(title = paste(\"Distribution of\", target_var, \"by\", group_var),\n",
        "           x = target_var, \n",
        "           y = ", ifelse(additional_options$subgroup_normalize, "\"Proportion\"", "\"Count\""), ") +\n",
        "      ", ifelse(additional_options$subgroup_facet, "theme(legend.position = \"none\")", "theme()"), "\n",
        "  } else if (\"", additional_options$subgroup_plot_type, "\" == \"density\") {\n",
        "    # Density plot\n",
        "    p <- ggplot(subgroup_data, aes_string(x = target_var, fill = group_var, color = group_var)) +\n",
        "      geom_density(alpha = 0.2) +\n",
        "      ", ifelse(additional_options$subgroup_facet, "facet_wrap(~ subgroup_data[[group_var]], scales = \"free_y\") +\n", ""),
        "      scale_fill_viridis_d() +\n",
        "      scale_color_viridis_d() +\n",
        "      theme_minimal() +\n",
        "      labs(title = paste(\"Density of\", target_var, \"by\", group_var),\n",
        "           x = target_var, y = \"Density\") +\n",
        "      ", ifelse(additional_options$subgroup_facet, "theme(legend.position = \"none\")", "theme()"), "\n",
        "  } else if (\"", additional_options$subgroup_plot_type, "\" == \"box\") {\n",
        "    # Boxplot\n",
        "    if (", ifelse(additional_options$subgroup_facet, "TRUE", "FALSE"), ") {\n",
        "      p <- ggplot(subgroup_data, aes_string(y = target_var, fill = group_var)) +\n",
        "        geom_boxplot(alpha = 0.7) +\n",
        "        facet_wrap(~ subgroup_data[[group_var]], scales = \"free_x\") +\n",
        "        scale_fill_viridis_d() +\n",
        "        theme_minimal() +\n",
        "        labs(title = paste(\"Boxplot of\", target_var, \"by\", group_var),\n",
        "             y = target_var) +\n",
        "        theme(legend.position = \"none\")\n",
        "    } else {\n",
        "      p <- ggplot(subgroup_data, aes_string(x = group_var, y = target_var, fill = group_var)) +\n",
        "        geom_boxplot(alpha = 0.7) +\n",
        "        scale_fill_viridis_d() +\n",
        "        theme_minimal() +\n",
        "        theme(axis.text.x = element_text(angle = 45, hjust = 1)) +\n",
        "        labs(title = paste(\"Boxplot of\", target_var, \"by\", group_var),\n",
        "             x = group_var, y = target_var)\n",
        "    }\n",
        "  }\n",
        "} else {\n",
        "  # For categorical target variables\n",
        "  # Calculate counts\n",
        "  count_data <- as.data.frame(table(subgroup_data[[group_var]], subgroup_data[[target_var]]))\n",
        "  names(count_data) <- c(\"group\", \"target\", \"count\")\n",
        "  \n",
        "  # Add proportion calculation if normalized\n",
        "  if (", ifelse(additional_options$subgroup_normalize, "TRUE", "FALSE"), ") {\n",
        "    count_data <- count_data %>%\n",
        "      group_by(group) %>%\n",
        "      mutate(proportion = count / sum(count)) %>%\n",
        "      ungroup()\n",
        "  }\n",
        "  \n",
        "  # Bar chart\n",
        "  if (", ifelse(additional_options$subgroup_facet, "TRUE", "FALSE"), ") {\n",
        "    p <- ggplot(count_data, aes(\n",
        "      x = target, \n",
        "      y = ", ifelse(additional_options$subgroup_normalize, "proportion", "count"), ", \n",
        "      fill = target\n",
        "    )) +\n",
        "      geom_col(alpha = 0.7) +\n",
        "      facet_wrap(~ group, scales = \"free_y\") +\n",
        "      scale_fill_viridis_d() +\n",
        "      theme_minimal() +\n",
        "      theme(\n",
        "        axis.text.x = element_text(angle = 45, hjust = 1),\n",
        "        legend.position = \"none\"\n",
        "      ) +\n",
        "      labs(\n",
        "        title = paste(\"Distribution of\", target_var, \"by\", group_var),\n",
        "        x = target_var, \n",
        "        y = ", ifelse(additional_options$subgroup_normalize, "\"Proportion\"", "\"Count\""), "\n",
        "      )\n",
        "  } else {\n",
        "    p <- ggplot(count_data, aes(\n",
        "      x = target, \n",
        "      y = ", ifelse(additional_options$subgroup_normalize, "proportion", "count"), ", \n",
        "      fill = group\n",
        "    )) +\n",
        "      geom_col(position = \"dodge\", alpha = 0.7) +\n",
        "      scale_fill_viridis_d() +\n",
        "      theme_minimal() +\n",
        "      theme(axis.text.x = element_text(angle = 45, hjust = 1)) +\n",
        "      labs(\n",
        "        title = paste(\"Distribution of\", target_var, \"by\", group_var),\n",
        "        x = target_var, \n",
        "        y = ", ifelse(additional_options$subgroup_normalize, "\"Proportion\"", "\"Count\""), "\n",
        "      )\n",
        "  }\n",
        "}\n\n",
        
        "# Display the plot\n",
        "print(p)\n\n",
        
        "# Calculate statistics by group\n",
        "cat(\"\\n\\n### Summary Statistics by Group\\n\\n\")\n\n",
        
        "if (is.numeric(subgroup_data[[target_var]])) {\n",
        "  # For numeric target, calculate statistics by group\n",
        "  group_stats <- aggregate(\n",
        "    subgroup_data[[target_var]],\n",
        "    by = list(Group = subgroup_data[[group_var]]),\n",
        "    FUN = function(x) c(\n",
        "      Count = length(x),\n",
        "      Missing = sum(is.na(x)),\n",
        "      Min = min(x, na.rm = TRUE),\n",
        "      Q1 = quantile(x, 0.25, na.rm = TRUE),\n",
        "      Median = median(x, na.rm = TRUE),\n",
        "      Mean = mean(x, na.rm = TRUE),\n",
        "      Q3 = quantile(x, 0.75, na.rm = TRUE),\n",
        "      Max = max(x, na.rm = TRUE),\n",
        "      SD = sd(x, na.rm = TRUE)\n",
        "    )\n",
        "  )\n",
        "  \n",
        "  # Convert to dataframe\n",
        "  stats_df <- do.call(data.frame, group_stats)\n",
        "  names(stats_df) <- c(\"Group\", \"Count\", \"Missing\", \"Min\", \"Q1\", \"Median\", \"Mean\", \"Q3\", \"Max\", \"SD\")\n",
        "  \n",
        "  # Round numeric columns\n",
        "  stats_df[, 4:10] <- round(stats_df[, 4:10], 2)\n",
        "  \n",
        "  # Display table\n",
        "  knitr::kable(stats_df)\n",
        "} else {\n",
        "  # For categorical target, calculate frequencies by group\n",
        "  group_freq <- table(subgroup_data[[group_var]], subgroup_data[[target_var]])\n",
        "  group_percent <- prop.table(group_freq, 1) * 100\n",
        "  \n",
        "  # Display frequency table\n",
        "  cat(\"#### Frequency Counts\\n\\n\")\n",
        "  print(knitr::kable(group_freq))\n",
        "  \n",
        "  # Display percentage table\n",
        "  cat(\"\\n\\n#### Percentages (Row %)\\n\\n\")\n",
        "  print(knitr::kable(round(group_percent, 1)))\n",
        "}\n",
        "```\n\n"
      )
    } else { "" },
    
    if (additional_options$include_models && !is.null(additional_options$model_recommendations)) {
      paste0(
        "## Model Recommendations\n\n",
        "```{r model_recommendations, echo=FALSE}\n",
        "# Extract model recommendations\n",
        "model_rec <- additional_options$model_recommendations\n\n",
        
        "# Display question\n",
        "cat(\"### Analysis Question\\n\\n\")\n",
        "cat(model_rec$question, \"\\n\\n\")\n\n",
        
        "# Display task identification\n",
        "cat(\"### Task Identification\\n\\n\")\n",
        "cat(\"Task Type: \", model_rec$task_identification$task_type, \"\\n\")\n",
        "if (!is.null(model_rec$task_identification$potential_targets)) {\n",
        "  cat(\"Potential Target Variables: \", paste(model_rec$task_identification$potential_targets, collapse = \", \"), \"\\n\")\n",
        "}\n",
        "cat(\"\\n\")\n\n",
        
        "# Display recommended models\n",
        "cat(\"### Recommended Models\\n\\n\")\n",
        "for (i in seq_along(model_rec$recommended_models)) {\n",
        "  model <- model_rec$recommended_models[[i]]\n",
        "  cat(\"#### \", i, \". \", model$name, \"\\n\\n\", sep = \"\")\n",
        "  cat(model$description, \"\\n\\n\")\n",
        "}\n\n",
        
        "# Display evaluation metrics\n",
        "cat(\"### Recommended Evaluation Metrics\\n\\n\")\n",
        "for (i in seq_along(model_rec$evaluation_metrics)) {\n",
        "  metric <- model_rec$evaluation_metrics[[i]]\n",
        "  cat(\"- **\", metric$name, \"**: \", metric$description, \"\\n\", sep = \"\")\n",
        "}\n",
        "cat(\"\\n\")\n\n",
        
        "# Display implementation code if available and requested\n",
        "if (!is.null(model_rec$implementation$code_examples)) {\n",
        "  cat(\"### Implementation Code Examples\\n\\n\")\n",
        "  cat(\"```r\\n\")\n",
        "  cat(model_rec$implementation$code_examples, \"\\n\")\n",
        "  cat(\"```\\n\\n\")\n",
        "}\n",
        "```\n\n"
      )
    } else { "" },
    
    "## Conclusions and Recommendations\n\n",
    "Based on this exploratory data analysis, here are some key observations and potential next steps:\n\n",
    
    "```{r conclusions, echo=FALSE}\n",
    "# Dataset size\n",
    "cat(\"- This dataset contains\", nrow(data), \"observations and\", ncol(data), \"variables.\\n\")\n\n",
    
    "# Missing values\n",
    "if (missing_result$overall$missing_percent > 0) {\n",
    "  cat(\"- Missing data: \", round(missing_result$overall$missing_percent, 1), \"% of the data is missing.\\n\")\n",
    "  \n",
    "  # Identify columns with high missingness\n",
    "  high_missing <- sapply(missing_result$columns, function(x) x$missing_percent > 20)\n",
    "  if (any(high_missing)) {\n",
    "    high_missing_cols <- names(missing_result$columns)[high_missing]\n",
    "    cat(\"  * Variables with high missingness: \", paste(high_missing_cols, collapse = \", \"), \"\\n\")\n",
    "    cat(\"  * Consider imputation techniques or removing these variables if appropriate.\\n\")\n",
    "  }\n",
    "} else {\n",
    "  cat(\"- The dataset is complete with no missing values.\\n\")\n",
    "}\n\n",
    
    "# Correlations\n",
    "if (!is.null(corr_result$strong_correlations) && nrow(corr_result$strong_correlations) > 0) {\n",
    "  cat(\"- Strong correlations were found:\\n\")\n",
    "  for (i in 1:min(5, nrow(corr_result$strong_correlations))) {\n",
    "    cat(\"  * \", corr_result$strong_correlations$var1[i], \"and\", \n",
    "        corr_result$strong_correlations$var2[i], \":\", \n",
    "        round(corr_result$strong_correlations$correlation[i], 2), \"\\n\")\n",
    "  }\n",
    "  if (nrow(corr_result$strong_correlations) > 0) {\n",
    "    cat(\"  * Consider feature selection or dimensionality reduction techniques.\\n\")\n",
    "  }\n",
    "}\n\n",
    
    "# Outliers\n",
    "has_outliers <- FALSE\n",
    "for (method in names(outlier_result$summary)) {\n",
    "  if (method != \"per_variable\" && outlier_result$summary[[method]] > 0) {\n",
    "    has_outliers <- TRUE\n",
    "    break\n",
    "  }\n",
    "}\n\n",
    
    "if (has_outliers) {\n",
    "  cat(\"- Outliers were detected in the dataset.\\n\")\n",
    "  if (!is.null(outlier_result$summary$per_variable)) {\n",
    "    # Only consider numeric variables for outliers\n",
    "    numeric_cols <- sapply(data, is.numeric)\n",
    "    if (any(numeric_cols)) {\n",
    "      numeric_var_names <- names(data)[numeric_cols]\n",
    "      per_var_cols <- intersect(colnames(outlier_result$summary$per_variable), numeric_var_names)\n",
    "      \n",
    "      if (length(per_var_cols) > 0) {\n",
    "        per_var_data <- outlier_result$summary$per_variable[, per_var_cols, drop=FALSE]\n",
    "        vars_with_outliers <- apply(per_var_data, 2, sum) > 0\n",
    "        \n",
    "        if (any(vars_with_outliers)) {\n",
    "          outlier_vars <- names(vars_with_outliers)[vars_with_outliers]\n",
    "          cat(\"  * Variables with outliers: \", paste(outlier_vars, collapse = \", \"), \"\\n\")\n",
    "        }\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "  cat(\"  * Consider investigating these outliers and potentially applying transformations or removing them if they represent errors.\\n\")\n",
    "} else {\n",
    "  cat(\"- No significant outliers were detected in the dataset.\\n\")\n",
    "}\n\n",
    
    "# Next steps\n",
    "cat(\"- Potential next steps:\\n\")\n",
    "cat(\"  * Data cleaning: Handle missing values and outliers.\\n\")\n",
    "cat(\"  * Feature engineering: Create new variables or transform existing ones.\\n\")\n",
    "cat(\"  * Modeling: Select appropriate algorithms based on the data characteristics.\\n\")\n",
    "```\n\n",
    
    "This report was generated automatically using the `EDAhelper` package. For more customized analysis, you can use the individual functions from the package.\n"
  )
  
  # Write the R Markdown content to the file
  writeLines(rmd_content, rmd_file)
  
  # Render the R Markdown file to HTML
  rmarkdown::render(
    input = rmd_file,
    output_file = output_file,
    quiet = TRUE
  )
  
  # Return the file path invisibly
  return(invisible(output_file))
}